site:
    title: "OTZephyr"
    subtitle: "生活不止眼前的代码，还有老婆和孩子"
    limit: 10
    theme: theme
    lang: zh-cn
    url: "https://zephyrjung.github.io/"
    comment: username
    logo: "-/images/avatar.jpeg"
    # link: "{category}/{year}/{month}/{day}/{title}.html"
    # link: "{year}{month}{day}{hour}{minute}{second}.html"
    # root: "/blog"

authors:
    me:
        name: "Zephyr Jung"
        intro: "A Poorgrammer"
        avatar: "-/images/avatar.jpeg"

build:
    # output: "public"
    port: 8000
    # Copied files to public folder when build
    copy:
        - "source/images"
    # Excuted command when use 'ink publish'
    publish: |
        git add . -A
        git commit -m "update"
        git push origin
